os: osx
osx_image: xcode13.2
language: swift
script: 
  - xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY=""CODE_SIGNING_REQUIRED=YES
  - xcodebuild clean build test -workspace EssentialApp/EssentialApp.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY=""CODE_SIGNING_REQUIRED=YES
